// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAeF4N2rGvpubj0vTcLJmsCTytCe1FkMw',
    appId: '1:304235558047:web:d039578ffa3f5dfd9e9eaa',
    messagingSenderId: '304235558047',
    projectId: 'hw4mob',
    authDomain: 'hw4mob.firebaseapp.com',
    storageBucket: 'hw4mob.firebasestorage.app',
    measurementId: 'G-L8TF6JHVER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1sin7tFsVQxyJ2EaJRUOrfcaxZuCvlIE',
    appId: '1:304235558047:android:4c9c0e1bc8a641d99e9eaa',
    messagingSenderId: '304235558047',
    projectId: 'hw4mob',
    storageBucket: 'hw4mob.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUU7z-qv1cHut17UXn6-gji0QVUaWKV9M',
    appId: '1:304235558047:ios:fcd528c38c939d659e9eaa',
    messagingSenderId: '304235558047',
    projectId: 'hw4mob',
    storageBucket: 'hw4mob.firebasestorage.app',
    iosBundleId: 'com.example.flutterHwMob4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUU7z-qv1cHut17UXn6-gji0QVUaWKV9M',
    appId: '1:304235558047:ios:fcd528c38c939d659e9eaa',
    messagingSenderId: '304235558047',
    projectId: 'hw4mob',
    storageBucket: 'hw4mob.firebasestorage.app',
    iosBundleId: 'com.example.flutterHwMob4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAeF4N2rGvpubj0vTcLJmsCTytCe1FkMw',
    appId: '1:304235558047:web:7a3bbb9e0cd704c19e9eaa',
    messagingSenderId: '304235558047',
    projectId: 'hw4mob',
    authDomain: 'hw4mob.firebaseapp.com',
    storageBucket: 'hw4mob.firebasestorage.app',
    measurementId: 'G-2JR1XZ8HDS',
  );
}
